# Generated by Django 5.2 on 2025-04-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_workers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='nev',
            new_name='kliens',
        ),
    ]
