# Generated by Django 5.2 on 2025-04-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_nev_appointments_kliens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='kliens',
            new_name='nev',
        ),
    ]
